### PR TITLE
Update ode function

### PR DESCRIPTION
**Pull request by teddygroves**
This change uses the new ode functions introduced in cmdstan 2.24, and the fact we are now committed to using the modular rate law framework to simplify Maud, removing the need to automatically generate Stan code.

The main reason for this change is that at present the code generation functionality in Maud is hard to understand and prone to silent errors. The present design with a custom Stan model for each user input also introduces unnecessary complexity - we have to follow the generated code around, make sure it is written to a sensible place, etc. With this design, the workflow is a lot closer to the standard for probabilistic programming with Stan, albeit with a pretty long and complicated Stan program.

A second benefit of this change is that the output and input become more structured, with e.g. `kcats` as a category of model variables compared with the old `kinetic_parameters`.

The downside is that the Stan code needs to get a bit more complicated in order to handle the work that was previously done in code generation. I didn't notice any difference in performance but its also possible that there will be some overhead from doing lookups and copies for things that are currently hardcoded. On balance I think the tradeoff is worth it - I think the code is overall simpler and performance-wise we have bigger fish to fry for the time being.

I have implemented competitive inhibition but not allosteric modification, as this didn't seem to be implemented in in Maud for the modular rate law at the moment - @NicholasCowie maybe you know if this is really the case?

To run this version you will need to have cmdstan 2.24.0 or later installed. You can do this with the `install_cmdstan` command that comes with cmdstanpy as follows:

```
install_cmdstan -v 2.24.0
```

### CODE REVIEW

**Comment by NicholasCowie** [comment]
I thought I merged the subunit branch into Master, but it’s only local at the moment. I’ll chuck it up this weekend

**Comment by NicholasCowie** [comment]
We’re also using MWC allostery rather than the implementation in the modular rate law

**Comment by teddygroves** [comment]
> We’re also using MWC allostery rather than the implementation in the modular rate law

Ah yeah I thought so, but is it actually implemented right now?

**Comment by teddygroves** [comment]
> > We’re also using MWC allostery rather than the implementation in the modular rate law
> 
> Ah yeah I thought so, but is it actually implemented right now?

I see it is implemented - looks like I need to do some more work before this pr will be ready

**Comment by teddygroves** [comment]
OK I've now implemented allosteric inhibition and activation so this pr is ready for review.

**Comment by NicholasCowie** [comment]
@teddygroves I've implemented the subunits into this commit as well. Could you review that section prior to approval?

**Comment by teddygroves** [comment]
The subunits bit looks fine to me

**Pull request merged**
