### PR TITLE
Conserved moieties

### PR DESCRIPTION
**Pull request by NicholasCowie**
# Summary 
When solving a system of differential equations that constains states variables (balanced metabolites) who's sum remains constant throughout the simulation (such as adenosine phosphates), the probelm is numerically unstable. This is apparent when determining the jacobian of the system (a requirement for many algebra and ODE solvers) that either prevents a solution or where the pool changes in size throughout. 

Additionally, given an initial guess (which is how Maud operates), even if solved without numerical stability the pool will be a constant for the entire stan simulation. This is not desirable when there is no estimate of the metabolite concentration.

This PR introduces conserved moieties for balanced metabolites.

# Method

The proposed method solves for the independent set of balanced metabolites using a system of ODES

$$ \frac{dC_{independent balanced}}{dt} = 0$$

and calculates the dependent metabolite at each timestep using

$$ C_{dependent} =  C_{pool} - \sum C_{independent} $$

Where $C_{pool}$ is a parameter sampled from a log-normal distribution.

## Decisions
1. Reverting to using only an ODE solver:
- We cannot guarantee that the current approach which is an ODE solver nested in an Algebra Solver will not select a concentration larger than the sampled pool size. 
- Considering this is a new approach the more simple ODE only solution allows for easier debugging.

2. Not using the DAE solver
- The increased computational complexity over the ODE solver make is less desriable.
- Any transformations to the ODE solver may not be viable with the DAE solver.

NOTE! There are no tests implemented as of yet. An example is found in `data/example_input/example_model`

Checklist:

- [ ] Updated any relevant documentation
- [ ] Add an adr doc if appropriate
- [ ] Include links to any relevant issues in the description
- [ ] Unit tests passing
- [ ] Integration tests passing

### CODE REVIEW

**Review by carrascomj — CHANGES_REQUESTED** [review]
Still missing the out-of-sample model, which makes a fresh installation fail.

**Review by carrascomj — CHANGES_REQUESTED** [review]
The pool seems to be violated, need to investigate.

**Comment by NicholasCowie** [comment]
All other tests pass, problem is with safety.
Should we merge and deal with the safety error later?

**Review by carrascomj — APPROVED** [review]
LGTM, let's tackle docs and the safety CI failure in another PR.

**Pull request merged**
